export const lectures = [
  {
    number: 1,
    title: "CSS Review",
    date: "February 7, 2026 - [2026/02/07]",
    link: "https://najah.zoom.us/rec/share/GfE-yw1L3OrrpK7-4_NmH1Y3TwqD2L9-RE25ZGmRzAyy_fQp3EruBz7EmFxIPZs.f6yiy4x49yTmpgh8?startTime=1770466561000",
  },
  {
    number: 2,
    title: "Intro To BootStrap",
    date: "February 14, 2026 - [2026/02/14]",
    link: "https://najah.zoom.us/rec/share/jnXrUs1vDCTF4bRG0u16ZXqkDj1YrtQehoxVa2Ew5Ub48dmpmYC-75fMTHrUCfCi.45mSQeHfV4mw-sJD",
  },
  {
    number: 3,
    title: "React Project Bootstrap",
    date: "February 21, 2026 - [2026/02/21]",
    link: "https://najah.zoom.us/rec/share/7LRQXY2UVmUPSsKy1CGQSZcBMBHV3ytzP3WPhrN10jWZZxvfjTk7bTBpKIPqD6b_.JC_ZhQcYJ_AnfVmu",
  },
  {
    number: 4,
    title: "Import Vs. Require",
    date: "March 1, 2026 - [2026/03/01]",
    link: "https://najah.zoom.us/rec/play/i_cV4PdIHhkvTe6BQpdP_ZTJgqVLvc-HzaQJjQdWLXVQ7LXCrk9OmTTt67cMD9HKwfHPK_b2mYHsZJ2e.Ub-_vFTDfuTBlhVH?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2F3Xel1XxLfGbRfmLXL_6y4lkHfo3B3DHZxlm2fSU-pmNyiH1silzrjMYjBRPKV92r.Tso4KuNnG_EYph1h",
  },
  {
    number: 5,
    title: "Web Server & Versions",
    date: "March 10, 2026 - [2026/03/10]",
    link: "https://najah.zoom.us/rec/play/iCs7ng-5gt39DkIOay0NP0CDi6cvbmsjDWjcNZNTDUNqySTPoe5309SylRzRpEXAoh8qYm4OBeWqc7gn.nLEEW1qcAUpH50mW?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FbvRwZDo4JCzZ7Ok0nGcUopq6B-Aul1kcbj0qNU67GqXh1jOthjoVdJBnN5ApHsMB.6anX_3vDtdh3RY-t",
  },
  {
    number: 6,
    title: "Versions Constraints",
    date: "March 15, 2026 - [2026/03/15]",
    link: "https://najah.zoom.us/rec/play/n5huF3EDZ_UvvobanlkfDYPWSL5_QmZFFQbMGphmLTivdb3e5YfPskfhmrA0cqj-bfzLbigUoZOPEsR1.uFOMpkHSI17EnxJD?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2Fool2OfLz6-yvaxJw0ith0VzrgIskfS3c1B72rJbWNVVgR9ocSqph6OvW8vo-lZjc.Kwaf0k5q1_NpdHlJ",
  },
  {
    number: 7,
    title: "Moduels & Express",
    date: "March 17, 2026 - [2026/03/17]",
    link: "https://youtu.be/1uypE_42kuc",
  },
  {
    number: 8,
    title: "MySQL + Express + Postman",
    date: "March 24, 2026 - [2026/03/24]",
    link: "https://najah.zoom.us/rec/play/VPjZkLgkWOjY0M7wtVU4elCsoFqGJhS04iH31OWEB6rC4r6M7EKfh5tpy0z0f_8h85RkrDyuDC92ZyrD.1STR5SnVj8FabUUX?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FC1nDGd1iNVHSgnIDA3cloEFIJ0fuFAa_8T1uiDsc3BgAdPXFwTxSykR4UoXD2C6s.4_KFEa3PkPFjx8Uw",
  },
  {
    number: 9,
    title: "NoSQL + ORM + MongoDB",
    date: "March 29, 2026 - [2026/03/29]",
    link: "https://najah.zoom.us/rec/play/6PEnvD22ISycd9erOr8Ua86GO7fdqAs2p9lyVfGBClotYqjLUpvxlpWt4ImqRDap6-7F3sKXs5aMivw.SbJJcC9nYxnuUf5m?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FdOLqsDtJOM5s_G_TpBoMUpZsjg7lA5bbLK7WgJBD0OJ9_xv72_a-t8h8mp_fZH2e.g0W7SV_om4gddzxg",
  },
  {
    number: 10,
    title: "Sequelize + Sequelize CLI",
    date: "March 31, 2026 - [2026/03/31]",
    link: "https://najah.zoom.us/rec/play/zfimDT7i2YuL6MgNLH84Q0tUT2bOIu_pY4HuyFP0m6aEahO20xZmHUxCOR8RvuBeHmj9YeMmEgEw5-Q.PeaUk8gchSMtfIGe?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FybauS2yHDIfw0EWsSaSR-nOT7Gc9jv86spTWveJCBuOomxlO8fFt0nC3cTE7XZKn.5wMnkbhYnGNf3zVF",
  },
  {
    number: 11,
    title: "Querying & Associations.",
    date: "April 5, 2026 - [2026/04/05]",
    link: "https://najah.zoom.us/rec/play/wAG7NHCzxZlYCN5Fu6K12lN4Cs_HklqaT5cwu2O5wMhiFWYblT7Q0RA0ZaOYMrKFNDX0dkT6U8qJ_TUs.hfXeHG2geUo8wW6x?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2Fl9Cr9ZdFgytbnr9nxc5CmOIqFyazSQyDoDn0dvg8Vbv9rhA63gjfmyCWIFVstAz7.r_2zbECEcWjTQj2j",
  },
  {
    number: 12,
    title: "Routers & MVC.",
    date: "April 7, 2026 - [2026/04/07]",
    link: "https://najah.zoom.us/rec/play/Kv1NR2cwADOf1JkyqMN692CQLORygNyFpHprDnC-EMtPzO6byQhiuU9NabFY6DwgGVVVaNBi2mTjcHKJ.qlFfXkXK0ayaSlwG?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FVVNzC18cOG17ny2ERfXU8wyEAeio68tPX6JI37Frbc0kIM19FgoXLbNlt-BkVEXc.Ie2VcuQj6O_eJTDu",
  },
  {
    number: 13,
    title: "MongoDB",
    date: "April 11, 2026 - [2026/04/11]",
    link: "https://najah.zoom.us/rec/play/wg0dyt02WZ4HQiefqa8y_oWA1tcUFJH8SaoRciZdLQi6P8RsmUw6EHh7NpIU7DBcTiIpEsUhd4vxPLau.vacUxGi-_z5vEWil?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FtN0lGW0ok6MJ8UHpWTPNmlF5ksQAqT8owPnnxjg9hKvaspxZhLrjHyi53rIxeKg6.9GTjSAWIlX--SRX_",
  },
  {
    number: 14,
    title: "Frontend–Backend Integration Part-1",
    date: "April 21, 2026 - [2026/04/21]",
    link: "https://najah.zoom.us/rec/play/LzlbuKCpbq_Imn2q5SCc_Unl_NO4pplVoVpfBvIUL_6I8BIFdFqEaV8eVR3RsZPCYtoTV4OdcJoMM2VZ.zDmA_RlUzltJg1Sr?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2F3TYVzCeBSPBB9ZE7v9Twc2Fy_Gx8lyAkM5G4nuWchKQ4UjQjgyie9fzFITriGhUY.A3vR2nbFYNqZ9AiD",
  },
  {
    number: 15,
    title: "Frontend–Backend Integration Part-2",
    date: "April 26, 2026 - [2026/04/26]",
    link: "https://najah.zoom.us/rec/play/21KjLB0qHgArHBFKIG-2-DRwpBXGFUb78Fudk00_zmVVW7Q3SguVv9TutW7ENDlRQyvytZ6Cf75yF3LB.SlyA3KzK1cdqjrEa?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FCQ7BoHGWDcv-bflty7l1PqbGhVQwsxVxaO-VXzbjxg55pnQ4YSL9kEAPU-R0aqKg.d0jfQeemAsxX387t",
  },
  {
    number: 16,
    title: "DevOps & Deployment",
    date: "April 28, 2026 - [2026/04/28]",
    link: "https://najah.zoom.us/rec/play/Eac9HP-uW-ZVs0zEXiGZzvQxE326gNjjL0HmHQ-aFUe1Woya1PXcaODP7XGXBKgGjAfqYc5mWcgLejnv.1aF7sCTokGPQ47es?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2FQbSoSkHHCXyZYRw_6qhKbmPRWUhuAYN3SG7_6xS3cEZfBmQz2Q16BCyRSxgd14X7.kf1S_Gba2I2fVI6e",
  },
  {
    number: 17,
    title: "Solid Principles",
    date: "May 5, 2026 - [2026/05/05]",
    link: "https://najah.zoom.us/rec/play/zrLIZ2_3-YLqtiyYuRigaXSW9UjBTI-OvOwuuXnLu-36ifyqkhWIQcb8CHgJyfLT8BbZrv21drX7-DFS.nFZz-J10KgrY4iuN?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&oldStyle=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fnajah.zoom.us%2Frec%2Fshare%2Fb8mzwPz5DDL5KPbpcEcntp1LiXBh1naL1rAt5ZosGPEjBMvcSwniDvIXCsoY4pWJ.b2pTu2jtZIzgDX3Q",
  },
];